---
abstract: 'Update a Puppet environment in a Git branch'
author:
  - 'Manfred Stock <mstock@cpan.org>'
build_requires:
  Directory::Scratch: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::Class: '0'
  Test::Exception: '0'
  Test::More: '0.88'
  lib: '0'
  parent: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Puppet-Environment-Updater
no_index:
  file:
    - perlcritic.rc
requires:
  Carp: '0'
  File::pushd: '0'
  Git::Wrapper: '0'
  List::MoreUtils: '0'
  Log::Dispatchouli: '0'
  Moose: '0'
  MooseX::FollowPBP: '0'
  MooseX::Getopt: '0'
  MooseX::Types::Path::Class: '0'
  Path::Class::Dir: '0'
  Term::ANSIColor: '0'
  Try::Tiny: '0'
  namespace::autoclean: '0'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/mstock/App-Puppet-Environment-Updater.git
version: '0.001002'
x_generated_by_perl: v5.32.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
